### PR TITLE
Fixed bugs for implementing using recycle

### PR DESCRIPTION
**Pull request by domagojk**
server store$ using take(1) is created in its own driver

### CODE REVIEW

**Comment by leebenson** [comment]
@domagojk  - After `npm run build-server && node dist/server` and `curl`'ing, I get:

> Error Cannot read property 'store$' of undefined

Are you seeing the same?

**Comment by domagojk** [comment]
@leebenson that is strange, it works fine for me
I tried on my branch and I also tried cloning your branch again
```git clone https://github.com/leebenson/reactnow --depth 1 -b recyclejs --single-branch```

and it worked as expected 😕

**Comment by leebenson** [comment]
ah, I think I know why

> recyclejs            ^1.0.0  →   ^1.1.2

`package.json` needs updating... will try again

**Comment by domagojk** [comment]
Perhaps you didn't update recycle to latest version (1.1.2) ?

**Comment by leebenson** [comment]
works now 😄

**Pull request merged**
